name: alisatiyor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  #routing and navigation
  auto_route: ^7.8.4
  
  #state management
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  provider: ^6.1.2

  #grpc
  protobuf: ^3.1.0
  grpc: ^3.2.4
  fixnum: ^1.1.0
  
  #networking
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  curl_logger_dio_interceptor: ^1.0.0
  jwt_decoder: ^2.0.1

  #network connection
  connectivity_plus: ^6.0.2

  #serializing
  json_annotation: ^4.9.0
  equatable: ^2.0.5

  #utilities
  image_picker: ^1.0.7
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2


  #local storage
  hive: ^2.2.3
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.3

  flutter_image_compress: ^2.2.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  mockito: ^5.4.4
  web_socket_channel: ^3.0.0
  
  




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  auto_route_generator: ^7.3.2
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  very_good_analysis: ^5.1.0
  flutter_gen_runner: ^5.4.0
  rename: ^3.0.2
  http_mock_adapter: ^0.6.1

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/lottie/